# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b41315248adfc6a24ebe059dd4f8f9705297d72d4778da2884ca4a5a6d392a506773e6fd886a5f2514685fd3a43389680f6b72d02f5c4d1a41cec81264bff359

test:
  secret_key_base: 351acfdf55b8743f33490967bf3ec75e9d524846bc94e019c1e18c66756f4d31d4389ec757844e14d57ca98854745719e50b048d02c3d6626c2bc03b84cdbe55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
